#!/bin/bash

echo ""
tput setaf 4; echo "+-------------------------------------------------------+"
tput setaf 4; echo "|                                                       |"
tput setaf 4; echo "|  $(tput setaf 2)You can set the shell using $(tput setaf 3)chsh -s [path-to-zsh]$(tput sgr0)    $(tput setaf 4)|"
tput setaf 4; echo "|  $(tput setaf 2)Remember to logout and login! (or restart)$(tput setaf 4)           |"
tput setaf 4; echo "|                                                       |"
tput setaf 4; echo "+-------------------------------------------------------+"
echo ""
echo "   .-=========-."
echo "   \\'-=======-'/"
echo "   _|   .=.   |_"
echo "  ((|  {{1}}  |))"
echo "   '|         |'"
echo "    \\|  ' '| /"
echo "     | |\\ /| |"
echo "     | |( )| |"
echo "jgs  \\|-=-|/"
echo "      |   |"
echo "      |   |"
echo "      |   |"
echo "      |   |"
echo "     /     \\"
echo "    /       \\"
echo "   /_________\\"
echo "      |   |"
echo "     _|   |_"
echo "    (_______)"
echo ""
echo "All done!"

